# Generated by Django 3.0.6 on 2020-06-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('real_price', models.FloatField()),
                ('direct_labor', models.FloatField()),
                ('direct_wages', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('indirect_labor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='backend.Product')),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='backend.Product')),
            ],
        ),
    ]
