# Generated by Django 3.0.6 on 2020-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_average_profit_rate', models.FloatField()),
                ('estimated_average_profit_rate', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cost_price',
            new_name='indirect_wages',
        ),
    ]
