# Generated by Django 3.0.7 on 2020-06-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200604_2011'),
        ('backend', '0002_auto_20200605_1751'),
    ]

    operations = [
    ]
